apiVersion: v1
kind: Service
metadata:
  name: url-monitor
spec:
  type: {{ .Values.service.type }}
  selector:
    app: url-monitor
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000

